# .rubocop.yml
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Load extra cops you want active
require:
  - rubocop-minitest

AllCops:
  NewCops: enable

inherit_mode:
  merge:
    - Exclude

Minitest/AssertPredicate:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false  # set true if you want to enforce one assertion per test

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true
